"""Command line interface for generating pen plotter G-code from text."""
from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Iterable, List, Tuple

from .font_paths import FontLoader, LayoutSettings, layout_text
from .gcode import PlotterSettings, paths_to_gcode

PathType = List[Tuple[float, float]]


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate G-code for pen plotters from arbitrary text using TrueType fonts."
        )
    )
    parser.add_argument("text", nargs="?", help="Text to convert into G-code.")
    parser.add_argument(
        "--text-file",
        type=Path,
        help="Read the input text from a file instead of the command line.",
    )
    parser.add_argument(
        "--font",
        required=True,
        type=Path,
        help="Path to the .ttf font file to use.",
    )
    parser.add_argument(
        "--font-size",
        type=float,
        default=12.0,
        help="Target font size in millimetres (default: 12.0).",
    )
    parser.add_argument(
        "--line-spacing",
        type=float,
        default=1.3,
        help="Line spacing multiplier relative to the font size.",
    )
    parser.add_argument(
        "--char-spacing",
        type=float,
        default=0.0,
        help="Additional spacing between characters in millimetres.",
    )
    parser.add_argument(
        "--curve-tolerance",
        type=float,
        default=0.1,
        help="Maximum deviation in millimetres when approximating curves.",
    )
    parser.add_argument(
        "--travel-height",
        type=float,
        default=5.0,
        help="Pen height (mm) for travel moves.",
    )
    parser.add_argument(
        "--drawing-height",
        type=float,
        default=0.0,
        help="Pen height (mm) while drawing.",
    )
    parser.add_argument(
        "--travel-feed",
        type=float,
        default=3000.0,
        help="Feed rate (mm/min) for travel moves.",
    )
    parser.add_argument(
        "--drawing-feed",
        type=float,
        default=1200.0,
        help="Feed rate (mm/min) for drawing moves.",
    )
    parser.add_argument(
        "--origin-x",
        type=float,
        default=0.0,
        help="Translate the generated toolpath along the X axis (mm).",
    )
    parser.add_argument(
        "--origin-y",
        type=float,
        default=0.0,
        help="Translate the generated toolpath along the Y axis (mm).",
    )
    parser.add_argument(
        "--center",
        action="store_true",
        help="Center the text around the origin before applying offsets.",
    )
    parser.add_argument(
        "--comment",
        default="Generated by pen_plotter",
        help="Comment to embed at the top of the G-code file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output.gcode"),
        help="Destination path for the generated G-code (default: output.gcode).",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Print a short preview of the bounding box and total path length.",
    )
    return parser


def read_text(args: argparse.Namespace) -> str:
    if args.text_file is not None:
        return args.text_file.read_text(encoding="utf-8")
    if args.text is None:
        raise SystemExit("Either positional text or --text-file must be provided.")
    return args.text


def translate_paths(paths: List[PathType], dx: float, dy: float) -> List[PathType]:
    if dx == 0.0 and dy == 0.0:
        return paths
    return [[(x + dx, y + dy) for x, y in path] for path in paths]


def measure_paths(paths: Iterable[PathType]) -> tuple[float, float, float, float, float]:
    min_x = math.inf
    min_y = math.inf
    max_x = -math.inf
    max_y = -math.inf
    total_length = 0.0

    for path in paths:
        if not path:
            continue
        prev_x, prev_y = path[0]
        min_x = min(min_x, prev_x)
        min_y = min(min_y, prev_y)
        max_x = max(max_x, prev_x)
        max_y = max(max_y, prev_y)
        for x, y in path[1:]:
            min_x = min(min_x, x)
            min_y = min(min_y, y)
            max_x = max(max_x, x)
            max_y = max(max_y, y)
            total_length += math.hypot(x - prev_x, y - prev_y)
            prev_x, prev_y = x, y

    if min_x is math.inf:
        return 0.0, 0.0, 0.0, 0.0, 0.0

    return min_x, min_y, max_x, max_y, total_length


def main(argv: list[str] | None = None) -> None:
    parser = build_argument_parser()
    args = parser.parse_args(argv)

    layout_settings = LayoutSettings(
        font_size=args.font_size,
        line_spacing=args.line_spacing,
        character_spacing=args.char_spacing,
        curve_tolerance=args.curve_tolerance,
    )

    with FontLoader(str(args.font)) as font_loader:
        paths = layout_text(read_text(args), font_loader, layout_settings)

    if args.center:
        min_x, min_y, max_x, max_y, _ = measure_paths(paths)
        center_x = (min_x + max_x) / 2.0
        center_y = (min_y + max_y) / 2.0
        paths = translate_paths(paths, -center_x, -center_y)

    if args.origin_x != 0.0 or args.origin_y != 0.0:
        paths = translate_paths(paths, args.origin_x, args.origin_y)

    min_x, min_y, max_x, max_y, total_length = measure_paths(paths)

    if args.preview:
        print(
            f"Bounding box: ({min_x:.2f}, {min_y:.2f}) – ({max_x:.2f}, {max_y:.2f}) mm\n"
            f"Total drawing length: {total_length:.2f} mm"
        )

    settings = PlotterSettings(
        travel_height=args.travel_height,
        drawing_height=args.drawing_height,
        travel_feed_rate=args.travel_feed,
        drawing_feed_rate=args.drawing_feed,
        comment=args.comment,
    )

    gcode_lines = paths_to_gcode(paths, settings)
    args.output.write_text("\n".join(gcode_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    main()
