"""G-code generation helpers for pen plotters."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List, Sequence, Tuple

Point = Tuple[float, float]
Path = Sequence[Point]


@dataclass
class PlotterSettings:
    travel_height: float = 5.0
    drawing_height: float = 0.0
    travel_feed_rate: float = 3000.0
    drawing_feed_rate: float = 1200.0
    comment: str = "Generated by pen_plotter"


def paths_to_gcode(paths: Iterable[Path], settings: PlotterSettings) -> List[str]:
    gcode: List[str] = []
    gcode.append(f"; {settings.comment}")
    gcode.append("G90 ; Absolute positioning")
    gcode.append("G21 ; Units in millimeters")
    gcode.append(f"G0 Z{settings.travel_height:.3f}")

    current_feed: float | None = None
    current_z = settings.travel_height
    pen_is_down = False

    for path in paths:
        if len(path) < 2:
            continue

        start = path[0]
        gcode.append(_format_move("G0", start, None))
        if current_z != settings.travel_height:
            gcode.append(f"G0 Z{settings.travel_height:.3f}")
            current_z = settings.travel_height
        if not pen_is_down:
            if current_z != settings.drawing_height:
                gcode.append(
                    _format_z_move(
                        "G1",
                        settings.drawing_height,
                        settings.travel_feed_rate,
                    )
                )
                current_feed = settings.travel_feed_rate
                current_z = settings.drawing_height
            pen_is_down = True

        for point in path[1:]:
            gcode.append(
                _format_move(
                    "G1",
                    point,
                    settings.drawing_feed_rate if current_feed != settings.drawing_feed_rate else None,
                )
            )
            current_feed = settings.drawing_feed_rate

        gcode.append(
            _format_z_move(
                "G1",
                settings.travel_height,
                settings.travel_feed_rate if current_feed != settings.travel_feed_rate else None,
            )
        )
        current_feed = settings.travel_feed_rate
        current_z = settings.travel_height
        pen_is_down = False

    gcode.append("M2 ; Program end")
    return gcode


def _format_move(command: str, point: Point, feed_rate: float | None) -> str:
    x, y = point
    if feed_rate is not None:
        return f"{command} X{x:.3f} Y{y:.3f} F{feed_rate:.2f}"
    return f"{command} X{x:.3f} Y{y:.3f}"


def _format_z_move(command: str, z: float, feed_rate: float | None) -> str:
    if feed_rate is not None:
        return f"{command} Z{z:.3f} F{feed_rate:.2f}"
    return f"{command} Z{z:.3f}"
