"""G-code generation helpers for pen plotters."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List, Sequence, Tuple

Point = Tuple[float, float]
Path = Sequence[Point]


@dataclass
class PlotterSettings:
    """Configuration for converting paths into G-code commands.

    Feed rates are stored in mm/s to make GUI and CLI inputs friendlier while
    we keep emitting mm/min commands required by most firmware.
    """

    travel_height: float = 5.0
    drawing_height: float = 0.0
    travel_feed_rate: float = 50.0  # mm/s
    drawing_feed_rate: float = 20.0  # mm/s
    comment: str = "Generated by pen_plotter"


def paths_to_gcode(paths: Iterable[Path], settings: PlotterSettings) -> List[str]:
    gcode: List[str] = []
    gcode.append(f"; {settings.comment}")
    gcode.append("G90 ; Absolute positioning")
    gcode.append("G21 ; Units in millimeters")
    gcode.append(f"G0 Z{settings.travel_height:.3f}")

    current_feed: float | None = None
    current_z = settings.travel_height
    pen_is_down = False

    for path in paths:
        if len(path) < 2:
            continue

        start = path[0]
        gcode.append(_format_move("G0", start, None))
        if current_z != settings.travel_height:
            gcode.append(_format_z_move("G0", settings.travel_height, None))
            current_z = settings.travel_height
        if not pen_is_down:
            if current_z != settings.drawing_height:
                gcode.append(
                    _format_z_move(
                        "G1",
                        settings.drawing_height,
                        settings.travel_feed_rate,
                    )
                )
                current_feed = settings.travel_feed_rate
                current_z = settings.drawing_height
            pen_is_down = True

        for point in path[1:]:
            gcode.append(
                _format_move(
                    "G1",
                    point,
                    settings.drawing_feed_rate if current_feed != settings.drawing_feed_rate else None,
                )
            )
            current_feed = settings.drawing_feed_rate

        gcode.append(
            _format_z_move(
                "G0",
                settings.travel_height,
                settings.travel_feed_rate
                if current_feed != settings.travel_feed_rate
                else None,
            )
        )
        current_feed = settings.travel_feed_rate
        current_z = settings.travel_height
        pen_is_down = False

    gcode.append(_format_z_move("G0", settings.travel_height, None))
    gcode.append("M2 ; Program end")
    return gcode


def _format_move(command: str, point: Point, feed_rate: float | None) -> str:
    x, y = point
    if feed_rate is not None:
        feed_mm_min = feed_rate * 60.0
        return f"{command} X{x:.3f} Y{y:.3f} F{feed_mm_min:.2f}"
    return f"{command} X{x:.3f} Y{y:.3f}"


def _format_z_move(command: str, z: float, feed_rate: float | None) -> str:
    if feed_rate is not None:
        feed_mm_min = feed_rate * 60.0
        return f"{command} Z{z:.3f} F{feed_mm_min:.2f}"
    return f"{command} Z{z:.3f}"
