"""Desktop GUI for previewing text and exporting pen plotter G-code."""
from __future__ import annotations

import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk
from typing import List, Optional

from .font_paths import FontLoader, LayoutSettings, layout_text
from .gcode import PlotterSettings, paths_to_gcode
from .geometry import measure_paths, translate_paths


class PlotterGUI:
    """Tkinter application that mimics 3DWriter-style workflow."""

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Pen Plotter Studio")
        self.root.geometry("1080x720")
        self.root.minsize(960, 640)

        style = ttk.Style()
        # Use a modern-looking theme when available.
        if "clam" in style.theme_names():
            style.theme_use("clam")
        style.configure("TFrame", background="#f5f5f7")
        style.configure("TLabel", background="#f5f5f7")

        self.font_path: Optional[Path] = None
        self.preview_paths: Optional[List[List[tuple[float, float]]]] = None
        self._update_job: Optional[str] = None

        self.text_widget = tk.Text(root, wrap="word", height=12)
        self.font_label_var = tk.StringVar(value="Henüz font seçilmedi")
        self.font_size_var = tk.StringVar(value="12.0")
        self.line_spacing_var = tk.StringVar(value="1.3")
        self.char_spacing_var = tk.StringVar(value="0.0")
        self.curve_tol_var = tk.StringVar(value="0.1")
        self.travel_height_var = tk.StringVar(value="5.0")
        self.drawing_height_var = tk.StringVar(value="0.0")
        self.travel_feed_var = tk.StringVar(value="50")
        self.drawing_feed_var = tk.StringVar(value="20")
        self.origin_x_var = tk.StringVar(value="0.0")
        self.origin_y_var = tk.StringVar(value="0.0")
        self.comment_var = tk.StringVar(value="Generated by Pen Plotter Studio")
        self.center_var = tk.BooleanVar(value=True)

        self.status_var = tk.StringVar(value="Font seçin ve metninizi yazın.")

        self._build_layout()
        self._bind_events()
        self._redraw_preview()

    # ------------------------------------------------------------------ UI --
    def _build_layout(self) -> None:
        root = self.root
        root.columnconfigure(0, weight=0)
        root.columnconfigure(1, weight=1)
        root.rowconfigure(0, weight=1)

        sidebar = ttk.Frame(root, padding=20)
        sidebar.grid(row=0, column=0, sticky="nsw")
        sidebar.columnconfigure(0, weight=1)

        ttk.Label(sidebar, text="Metniniz", font=("Segoe UI", 10, "bold")).grid(
            row=0, column=0, sticky="w"
        )
        self.text_widget.configure(font=("Segoe UI", 10))
        self.text_widget.grid(row=1, column=0, sticky="nsew", pady=(6, 12))
        sidebar.rowconfigure(1, weight=1)

        button_row = ttk.Frame(sidebar)
        button_row.grid(row=2, column=0, sticky="ew", pady=(0, 12))
        button_row.columnconfigure(1, weight=1)

        ttk.Button(button_row, text="Font Aç", command=self._choose_font).grid(
            row=0, column=0, padx=(0, 8)
        )
        ttk.Label(button_row, textvariable=self.font_label_var, anchor="w").grid(
            row=0, column=1, sticky="ew"
        )

        settings = ttk.LabelFrame(sidebar, text="Parametreler", padding=(12, 6))
        settings.grid(row=3, column=0, sticky="ew", pady=(0, 12))
        settings.columnconfigure(1, weight=1)

        self._add_labeled_entry(settings, "Font boyutu (mm)", self.font_size_var, 0)
        self._add_labeled_entry(settings, "Satır aralığı", self.line_spacing_var, 1)
        self._add_labeled_entry(settings, "Harf aralığı (mm)", self.char_spacing_var, 2)
        self._add_labeled_entry(settings, "Eğri toleransı (mm)", self.curve_tol_var, 3)

        advanced = ttk.LabelFrame(sidebar, text="G-code Ayarları", padding=(12, 6))
        advanced.grid(row=4, column=0, sticky="ew")
        advanced.columnconfigure(1, weight=1)

        self._add_labeled_entry(advanced, "Travel Z (mm)", self.travel_height_var, 0)
        self._add_labeled_entry(advanced, "Drawing Z (mm)", self.drawing_height_var, 1)
        self._add_labeled_entry(advanced, "Travel hız (mm/sn)", self.travel_feed_var, 2)
        self._add_labeled_entry(advanced, "Drawing hız (mm/sn)", self.drawing_feed_var, 3)
        self._add_labeled_entry(advanced, "Origin X (mm)", self.origin_x_var, 4)
        self._add_labeled_entry(advanced, "Origin Y (mm)", self.origin_y_var, 5)
        self._add_labeled_entry(advanced, "Üst satır yorumu", self.comment_var, 6, columnspan=1)

        ttk.Checkbutton(
            sidebar,
            text="Metni merkezde hizala",
            variable=self.center_var,
            command=self._schedule_preview_update,
        ).grid(row=5, column=0, sticky="w", pady=(12, 6))

        ttk.Button(
            sidebar,
            text="G-code Kaydet",
            command=self._save_gcode,
        ).grid(row=6, column=0, sticky="ew")

        ttk.Label(sidebar, textvariable=self.status_var, wraplength=260).grid(
            row=7, column=0, sticky="we", pady=(12, 0)
        )

        preview_container = ttk.Frame(root, padding=(0, 20, 20, 20))
        preview_container.grid(row=0, column=1, sticky="nsew")
        preview_container.columnconfigure(0, weight=1)
        preview_container.rowconfigure(1, weight=1)

        ttk.Label(
            preview_container,
            text="Çizim önizlemesi",
            font=("Segoe UI", 11, "bold"),
        ).grid(row=0, column=0, sticky="w")

        self.canvas = tk.Canvas(
            preview_container,
            width=640,
            height=640,
            background="white",
            highlightthickness=1,
            highlightbackground="#d0d0d0",
        )
        self.canvas.grid(row=1, column=0, sticky="nsew", pady=(8, 0))

    def _add_labeled_entry(
        self,
        parent: ttk.LabelFrame,
        label: str,
        variable: tk.StringVar,
        row: int,
        columnspan: int = 1,
    ) -> None:
        ttk.Label(parent, text=label).grid(row=row, column=0, sticky="w", pady=2)
        entry = ttk.Entry(parent, textvariable=variable)
        entry.grid(row=row, column=1, columnspan=columnspan, sticky="ew", pady=2)
        entry.bind("<KeyRelease>", self._schedule_preview_update)

    # --------------------------------------------------------------- Events --
    def _bind_events(self) -> None:
        self.text_widget.bind("<KeyRelease>", self._schedule_preview_update)

    def _schedule_preview_update(self, *_: object) -> None:
        if self._update_job is not None:
            self.root.after_cancel(self._update_job)
        self._update_job = self.root.after(250, self._redraw_preview)

    # ----------------------------------------------------------- Previewing --
    def _redraw_preview(self) -> None:
        self._update_job = None
        self.canvas.delete("all")
        self._draw_grid()
        self.preview_paths = None

        if self.font_path is None:
            self.canvas.create_text(
                320,
                320,
                text="Lütfen önce bir .ttf font dosyası seçin",
                font=("Segoe UI", 12, "italic"),
                fill="#888888",
            )
            return

        text = self.text_widget.get("1.0", "end-1c")
        if not text.strip():
            self.canvas.create_text(
                320,
                320,
                text="Metin alanına yazı girin",
                font=("Segoe UI", 12, "italic"),
                fill="#888888",
            )
            return

        try:
            layout_settings = LayoutSettings(
                font_size=float(self.font_size_var.get()),
                line_spacing=float(self.line_spacing_var.get()),
                character_spacing=float(self.char_spacing_var.get()),
                curve_tolerance=float(self.curve_tol_var.get()),
            )
        except ValueError:
            self.status_var.set("Geçersiz sayı değeri girildi.")
            return

        try:
            with FontLoader(str(self.font_path)) as font_loader:
                paths = layout_text(text, font_loader, layout_settings)
        except Exception as exc:  # pragma: no cover - Tkinter message
            self.status_var.set(f"Font yüklenemedi: {exc}")
            return

        if not paths:
            self.status_var.set("Metin, çizilebilir yollar üretmedi.")
            return

        min_x, min_y, max_x, max_y, total_length = measure_paths(paths)
        if self.center_var.get():
            center_x = (min_x + max_x) / 2.0
            center_y = (min_y + max_y) / 2.0
            paths = translate_paths(paths, -center_x, -center_y)
            min_x, min_y, max_x, max_y, total_length = measure_paths(paths)

        # Fit into canvas with padding
        width = float(self.canvas.winfo_width() or 640)
        height = float(self.canvas.winfo_height() or 640)
        padding = 40.0
        span_x = max(max_x - min_x, 1e-6)
        span_y = max(max_y - min_y, 1e-6)
        scale = min((width - padding) / span_x, (height - padding) / span_y)
        offset_x = width / 2.0
        offset_y = height / 2.0

        for path in paths:
            if len(path) < 2:
                continue
            coords: list[float] = []
            for x, y in path:
                canvas_x = offset_x + x * scale
                canvas_y = offset_y - y * scale
                coords.extend((canvas_x, canvas_y))
            self.canvas.create_line(*coords, fill="#1f4b99", width=2.0, smooth=True)

        self.preview_paths = [list(path) for path in paths]
        bbox_text = (
            f"Önizleme: {max_x - min_x:.1f}×{max_y - min_y:.1f} mm, "
            f"toplam çizgi: {total_length:.1f} mm"
        )
        self.status_var.set(bbox_text)

    def _draw_grid(self) -> None:
        width = int(self.canvas.winfo_width() or 640)
        height = int(self.canvas.winfo_height() or 640)
        step = 40
        for x in range(0, width, step):
            color = "#e0e0e0" if x % 200 else "#c0c0c0"
            self.canvas.create_line(x, 0, x, height, fill=color)
        for y in range(0, height, step):
            color = "#e0e0e0" if y % 200 else "#c0c0c0"
            self.canvas.create_line(0, y, width, y, fill=color)

    # --------------------------------------------------------------- Actions --
    def _choose_font(self) -> None:
        initial_dir = Path.home() / "Desktop"
        file_path = filedialog.askopenfilename(
            title="TrueType font seç",
            filetypes=[("TrueType Font", "*.ttf"), ("OpenType Font", "*.otf"), ("Tüm dosyalar", "*.*")],
            initialdir=initial_dir if initial_dir.exists() else None,
        )
        if not file_path:
            return
        self.font_path = Path(file_path)
        self.font_label_var.set(self.font_path.name)
        self.status_var.set(f"Seçilen font: {self.font_path.name}")
        self._schedule_preview_update()

    def _save_gcode(self) -> None:
        if self.preview_paths is None or self.font_path is None:
            messagebox.showinfo(
                "Önce önizleme",
                "G-code almak için önce metni yazıp önizlemeyi oluşturmalısınız.",
            )
            return

        try:
            travel_height = float(self.travel_height_var.get())
            drawing_height = float(self.drawing_height_var.get())
            travel_feed = float(self.travel_feed_var.get())
            drawing_feed = float(self.drawing_feed_var.get())
            origin_x = float(self.origin_x_var.get())
            origin_y = float(self.origin_y_var.get())
        except ValueError:
            messagebox.showerror("Hata", "G-code ayarlarında geçersiz sayı değeri var.")
            return

        paths = [list(path) for path in self.preview_paths]
        if origin_x != 0.0 or origin_y != 0.0:
            paths = translate_paths(paths, origin_x, origin_y)

        settings = PlotterSettings(
            travel_height=travel_height,
            drawing_height=drawing_height,
            travel_feed_rate=travel_feed,
            drawing_feed_rate=drawing_feed,
            comment=self.comment_var.get(),
        )

        gcode_lines = paths_to_gcode(paths, settings)

        default_dir = Path.home() / "Desktop"
        save_path = filedialog.asksaveasfilename(
            defaultextension=".gcode",
            filetypes=[("G-code", "*.gcode"), ("Text", "*.txt"), ("All files", "*.*")],
            initialdir=default_dir if default_dir.exists() else None,
            initialfile="pen_plotter_output.gcode",
            title="G-code olarak kaydet",
        )
        if not save_path:
            return

        try:
            Path(save_path).write_text("\n".join(gcode_lines) + "\n", encoding="utf-8")
        except OSError as exc:
            messagebox.showerror("Kaydetme hatası", f"Dosya yazılamadı: {exc}")
            return

        messagebox.showinfo("Tamam", f"G-code kaydedildi:\n{save_path}")


def main() -> None:
    root = tk.Tk()
    app = PlotterGUI(root)
    root.mainloop()


if __name__ == "__main__":  # pragma: no cover - GUI entry point
    main()
